version: '2.1'

networks:
  servers:

services:

  balancer:
    build: .
    command: "lb"
    depends_on: 
      - server1
      - server2
      - server3
      - db
    networks:
      - servers
    ports:
      - "8090:8090"

  db:
    build: .
    command: "db"
    networks:
      - servers
    ports:
      - "8091:8091"

  server1:
    build: .
    depends_on: 
      - db
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    depends_on: 
      - db
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    depends_on: 
      - db
    networks:
      - servers
    ports:
      - "8082:8080"
